config/routes.rb
Depot::Application.routes.draw do
  get "pointsofsale/index"
  get 'admin' => 'admin#index'
  get "showcase/Home"
  get "showcase/Video"
  get "showcase/Idea"
  get "showcase/Legend"
  get "showcase/Workwithus"
  get "showcase/Presse"
  get "showcase/Mentions"
  get "maps/index"
  get "store/index"
  get "pointsofsale/index"
  get 'pointsofsale' => 'pointsofsale#index'
  get 'home' => 'showcase#Home'
  get 'idea' => 'showcase#Idea'
  get 'legend' => 'showcase#Legend'
  get 'workwithus' => 'showcase#Workwithus'
  get 'presse' => 'showcase#Presse'
  get 'mentions' => 'showcase#Mentions'
  get 'store' => 'store#index'
  get 'maps' => 'maps#index'
  get 'video' => 'showcase#Video'
  get 'summary' => 'orders#summary'
  get 'contact' => 'contacts#new'

  get 'paypal/checkout', to:'orders#paypal_checkout'
  post '/hook' => "orders#hook"

  get "instagram" => redirect("https://www.instagram.com/lebenefique/")
  get "facebook" => redirect("https://www.facebook.com/infusionslebenefique/?fref=ts")
  devise_for :users
scope '(:locale)' do
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :maps
  get '/users' => 'sessions#index', as: 'users'
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  root 'showcase#Home', as: 'showcase'
end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_one :cart

  validates :name, :address, :email, presence: true
  validates :email, uniqueness: true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  skip_before_action :admin_only, only: [:new, :create]
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:hook]
  protect_from_forgery except: [:hook]
  # GET /orders
  # GET /orders.json
  
  def hook
    params.permit! # Permit all Paypal input params
    puts params.to_json
    if params[:invoice]
      cart = Cart.find(params[:invoice])
      order = Order.create(paypal_customer_token: params[:payer_id], cart: cart, name: params[:first_name] + ' ' + params[:last_name], address: params[:address_street] + ' ' + params[:address_zip] + ' ' + params[:address_city] )
    end
    render nothing: true
  end

  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to store_url, notice:"Your cart is empty"
      return
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  def summary
  end

  # POST /orders
  # POST /orders.json
  def create
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def paypal_checkout
    @cart = Cart.find(session[:cart_id])
    @cart.update(user_id: current_user.id)
    values = {
      business: "merchant@gotealeaf.com",
      cmd: "_cart",
      upload: '2',
      notify_url: "http://f7d434f0.ngrok.io/hook",
      return: "http://localhost:3000",
      currency_code: 'EUR',
      invoice: @cart.id
    }
    @cart.line_items.each_with_index do |l, i|
      values["item_name_#{i+1}"] = l.product.title
      values["amount_#{i+1}"] = l.product.price.to_f
      values["quantity_#{i+1}"] = l.quantity
    end
    session[:cart_id] = nil
    redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <div class="form-group required">
      <%= f.label :nom, class: "control-label" %><br>
      <%= f.text_field :name, size: 40, class: "form-control" %>
    </div>
    <%= f.hidden_field :email, value: current_user.email, size: 40, class: "form-control" %>
    <div class="form-group required">
      <%= f.label :address, class: "control-label" %><br>
      <%= f.text_area :address, rows: 3, cols: 40, id: 'autocomplete', class: "form-control" %>
    </div>
  </div>
  <div class="form-actions">
    <div id="paypal_checkout">
      <%= link_to image_tag("https://www.paypal.com/fr_XC/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(:cart_id => session[:cart_id])%>
      <%= f.submit 'Place Order'%>
    </div>
  </div>
<% end %>
<script>
  function initAutocomplete() {
    // Create the autocomplete object, restricting the search to geographical
    // location types.
    autocomplete = new google.maps.places.Autocomplete(
        (document.getElementById('autocomplete')),
        {types: ['geocode']});
    autocomplete.addListener('place_changed', fillInAddress);
  }

  function fillInAddress() {
    // Get the place details from the autocomplete object.
    var place = autocomplete.getPlace();
  
    for (var component in componentForm) {
      document.getElementById(component).value = '';
      document.getElementById(component).disabled = false;
    }
  
    // Get each component of the address from the place details
    // and fill the corresponding field on the form.
    for (var i = 0; i < place.address_components.length; i++) {
      var addressType = place.address_components[i].types[0];
      if (componentForm[addressType]) {
        var val = place.address_components[i][componentForm[addressType]];
        document.getElementById(addressType).value = val;
      }
    }
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyChlLKUJvuUVdSkBvg7Mf1UhdjRoMyRPjs&libraries=places&callback=initAutocomplete"></script>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="to-margin">
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
</div>

app/views/orders/new.html.erb
<div class="to-margin">

  <h1>New order</h1>
  
  <div class="depot_form">
    <fieldset>
      <legend> Please enter Your Details</legend>
      <%= render 'form' %>
    </fieldset>
  </div>
  
  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/summary.html.erb
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>