config/routes.rb
Depot::Application.routes.draw do
  get "pointsofsale/index"
  get 'admin' => 'admin#index'
  get "showcase/Home"
  get "showcase/Video"
  get "showcase/Idea"
  get "showcase/Legend"
  get "showcase/Workwithus"
  get "showcase/Presse"
  get "showcase/Mentions"
  get "maps/index"
  get "store/index"
  get "pointsofsale/index"
  get 'pointsofsale' => 'pointsofsale#index'
  get 'home' => 'showcase#Home'
  get 'idea' => 'showcase#Idea'
  get 'legend' => 'showcase#Legend'
  get 'workwithus' => 'showcase#Workwithus'
  get 'presse' => 'showcase#Presse'
  get 'mentions' => 'showcase#Mentions'
  get 'store' => 'store#index'
  get 'maps' => 'maps#index'
  get 'video' => 'showcase#Video'
  get 'summary' => 'orders#summary'
  get 'contact' => 'contacts#new'

  get 'paypal/checkout', to:'orders#paypal_checkout'
  post '/hook' => "orders#hook"

  get "instagram" => redirect("https://www.instagram.com/lebenefique/")
  get "facebook" => redirect("https://www.facebook.com/infusionslebenefique/?fref=ts")
  devise_for :users
scope '(:locale)' do
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :maps
  get '/users' => 'sessions#index', as: 'users'
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  root 'showcase#Home', as: 'showcase'
end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id, quantity)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity = current_item.quantity + quantity
    else
      current_item = line_items.build(product_id: product_id)
      if quantity > 1
        current_item.quantity = current_item.quantity + quantity - 1
      end
    end
    current_item
  end
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
  def cart_count
    line_items.to_a.sum {|item| item.cart_count}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :edit, :destroy, :update, :show]
  skip_before_action :admin_only, only: [:new, :create, :edit, :destroy, :update, :show]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end%>

<div class="carts">
<header>
  <div class="container">
    <div class="row">
      <div class="head-div col-xs-3 col-xs-offset-5 col-lg-3 col-lg-offset-5">
        <h1> Votre panier </h1>
    </div>
  </div>
</header>
<section class="cart-section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-0 resume-cart">
        <h1 style="float:left;position:relative;top:-50px;left:90px;"> Panier </h1>
        <hr style="height:1px; width: 100%;border:none;color:#333;background-color:#333;">
        <table class="test">
          <tr>
            <th id="nothing"> </th>
            <th id="article">Article</th>
            <th id="quantite">Quantite</th>
            <th id="prix-article">Prix article</th>
            <th id="prix-total">Prix total</th>
          </tr>
          <% @cart.line_items.each do |item| %>
          <tr>
            <td headers="nothing"> <%= image_tag(item.product.image_url, :class => 'the_img') %></td>
            <td headers="article">  <%= item.product.title %><br/><%= link_to 'Supprimer', item, :method => :delete, :confirm=>'Are you Sure?' %></td>
            <td headers="quantite"> <%= item.quantity%></td>
            <td headers="prix-article"><%=number_to_currency(item.product.price)%></td>
            <td headers="prix-total"><%= number_to_currency(item.total_price)%></td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="total-and-checkout col-md-3 col-md-offset-4">
        <h1 style="position:relative; top:-30px;"> Résumé </h1>
        <hr style="height:180px; width: 1px;border:none;color:#333;background-color:#333; position:absolute; top: -60px;">
        <tr class="total_line">
          <td colspan="2">Total</td>
          <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
        </tr>
        <br />
        <%= link_to 'Empty cart', @cart, method: :delete, data: {confirm:'Are you sure?'} %> |
        <%= link_to 'Back', store_path %>
        <div class="form-actions">
          <div id="paypal_checkout">
            <%= link_to image_tag("https://www.paypal.com/fr_XC/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(:cart_id => session[:cart_id])%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>