config/routes.rb
Depot::Application.routes.draw do
  get "pointsofsale/index"
  get 'admin' => 'admin#index'
  get "showcase/Home"
  get "showcase/Video"
  get "showcase/Idea"
  get "showcase/Legend"
  get "showcase/Workwithus"
  get "showcase/Presse"
  get "showcase/Mentions"
  get "maps/index"
  get "store/index"
  get "pointsofsale/index"
  get 'pointsofsale' => 'pointsofsale#index'
  get 'home' => 'showcase#Home'
  get 'idea' => 'showcase#Idea'
  get 'legend' => 'showcase#Legend'
  get 'workwithus' => 'showcase#Workwithus'
  get 'presse' => 'showcase#Presse'
  get 'mentions' => 'showcase#Mentions'
  get 'store' => 'store#index'
  get 'maps' => 'maps#index'
  get 'video' => 'showcase#Video'
  get 'summary' => 'orders#summary'
  get 'contact' => 'contacts#new'

  get 'paypal/checkout', to:'orders#paypal_checkout'
  post '/hook' => "orders#hook"

  get "instagram" => redirect("https://www.instagram.com/lebenefique/")
  get "facebook" => redirect("https://www.facebook.com/infusionslebenefique/?fref=ts")
  devise_for :users
scope '(:locale)' do
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :maps
  get '/users' => 'sessions#index', as: 'users'
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  root 'showcase#Home', as: 'showcase'
end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id, quantity)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity = current_item.quantity + quantity
    else
      current_item = line_items.build(product_id: product_id)
      if quantity > 1
        current_item.quantity = current_item.quantity + quantity - 1
      end
    end
    current_item
  end
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
  def cart_count
    line_items.to_a.sum {|item| item.cart_count}
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :telephone,  :validate => /\d[0-9]\)*\z/
  attribute :object
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Website Contact Form",
      :to => "yanisisma@msn.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  def total_price
    product.price * quantity
  end

  def cart_count
    quantity
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_one :cart

  validates :name, :address, :email, presence: true
  validates :email, uniqueness: true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item
 validates :title, :description, :image_url, presence: true
 validates :price, :product_line, numericality: {greater_than_or_equal_to: 0.01}
 validates :title, uniqueness: true
 validates :image_url, allow_blank: true, format: {
 	with:  %r{\.(gif|jpg|png)\Z}i,
	message: 'must be a URL for GIF, JPG, or PNG image.'
	}
  def self.latest
    Product.order(:updated_at).last
  end

 private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Item present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  skip_before_action :admin_only, only: [:show]
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to maps_url, notice: 'Map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to maps_url, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/svg_helper.rb
module SvgHelper
# Rails
 def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
     '(not found)'
   end
   # Middleman
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="to-margin">
<h1>Bonjour Administrateur</h1>

It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <title><%= yield(:title) %></title>
   <meta charset="utf-8"/>
   <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
   <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1, user-scalable=no"/>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script>
new WOW().init();
</script>
<body class="<%= controller.controller_name %>">
  <div id="layout-main-page">
    <div class="header-zone">
    <div class="fix-menu">
<nav id="topmenu">
    <li><a href="#" class="class-menu"><div class="line-menu elem-one"></div><div class="line-menu elem-two"></div><div class="line-menu elem-three"></div></a>
      <div id="submenu">
        <ul>
          <li class="limen"><%= link_to 'ACCUEIL', home_path %></li>
          <li class="limen"><%= link_to'IDÉE', idea_path %></li>
          <li class="limen"><%= link_to'LÉGENDE', legend_path %></li>
          <li class="limen"><%= link_to'PRODUITS', store_path %></li>
          <li class="limen"><%= link_to 'POINTS DE VENTE', pointsofsale_path,  data: { no_turbolink: false } %></li>
          <li class="limen"><%= link_to'TRAVAILLER AVEC NOUS', workwithus_path %></li>
          <li class="limen"><%= link_to'CONTACT', contact_path %></li>
          <li class="limen"><img src="/elem/Btn-langue.png" alt="bouton-langue" /></li>
          <li class="limen"> <%= link_to image_tag("/elem/shopping-bag.png", :class =>"panier-header-menu"), current_cart %></li>
          <div class="cart-count-menu">
            <% if current_cart %>
              <%= current_cart.cart_count%>
            <% end %>
          </div>
          <% if current_user && current_user.admin? %>
          <li><%= link_to'Orders', orders_path %></li>
          <li><%= link_to'Products', products_path %></li>
          <li><%= link_to'Users', users_path %></li>
          <li><%= link_to'Shops', maps_path %></li>
          <% end %>
          <% if current_user && !current_user.admin? %>
          <li class="limen"><a href="#">MON COMPTE</a></li>
          <% end %>
          <% if current_user %>
          <li><p class="log-buttons"><%= button_to 'deconnexion', destroy_user_session_path, method: :delete %></p></li>
          <% else %>
          <li class="log-buttons"><p><a data-toggle="modal" data-target="#myModal2">INSCRIPTION / CONNEXION</a></p></li>
          <% end %>
          <li><%= link_to instagram_path do image_tag("/elem/insta.png", onmouseover: "this.src='#{asset_path('/elem/insta-hover.png')}'", onmouseout: "this.src='#{asset_path('/elem/insta.png')}'", width: '25') end %><%= link_to facebook_path do image_tag("/elem/facebook.png", onmouseover: "this.src='#{asset_path('/elem/facebook-hover.png')}'", onmouseout: "this.src='#{asset_path('/elem/facebook.png')}'", width: '13') end %></li>
        </ul>
      </div>
    </nav>
<h1 class="top-title-menu"><%= yield(:title) %></h1>
</div>
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>
<%# app/views/showcase/Idea.html.erb%>
<% if @check %>
    <div class="img-top hidden-xs">
      <%= link_to image_tag("/elem/logo2.png"), home_path %>
  </div>
  <div class="img-top visible-xs">
      <%= link_to image_tag("/elem/logo-mobile.png"), home_path %>
  </div>
<% else %>
    <div class="img-head margin-img hidden-xs">
      <%= link_to image_tag("/elem/logo2.png"), home_path %>
    </div>
    <div class="img-head margin-img visible-xs">
        <%= link_to image_tag("/elem/logo-mobile.png"), home_path %>
    </div>
<% end %>
</div>
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
  <div class="modal-dialog" role="document" style="width: 90%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="log-and-sign">
          <div class="container">
            <div class="row">
              <div class="col-xs-6">
                <div class="connect-account">
                  <h2>Connexion</h2>
                  <p> pour les clients ayant deja un compte</p>
                  <%= form_for(:user, url: session_path(:user)) do |f| %>
                  <div class="form-inputs">
                    <div class="form-group required">
                      <%= f.label :'E-mail', class: "control-label" %>
                      <%= f.email_field :email, class: "form-control", id: "email" %>
                    </div>
                    <div class="form-group required">
                      <%= f.label :'Mot de passe', class: "control-label" %>
                      <%= f.password_field :password, class: 'form-control', id: 'password' %>
                    </div>
                  </div>
                  <div class="form-actions">
                    <%= f.submit :"Log in" %>
                  </div>
                  <%= render "devise/shared/links" %>
                <% end %>
              </div>
            </div>
                <div class="col-xs-6">
                  <div class="create-account">
                    <div class="deport_form">
                      <h2>Creer un compte</h2>
                      <p> Merci d'entrer les informations suivantes pour creer un compte</p>
                      <%= form_for(:user, url: registration_path(:user)) do |f| %>
                        <div class="form-inputs">
                          <div class="form-group required">
                            <%= f.label :'E-mail', class: "control-label" %>
                            <%= f.email_field :email, class: "form-control", id: "email" %>
                          </div>
                          <div class="form-group required">
                            <%= f.label :'Mot de passe', class: "control-label" %>
                            <%= f.password_field :password, class: 'form-control', id: 'password' %>
                          </div>
                          <div class="form-group required">
                            <%= f.label :'Confirmation du mot de passe', class: "control-label" %>
                            <%= f.password_field :password_confirmation, class: 'form-control', id: 'password_confirmation' %>
                          </div>
                        </div>
                        <div class="actions">
                          <%= f.submit "S'inscrire" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<%= yield %>
</div>
<footer class="footer-app">
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-0 col-xs-12 fixed-middle">
        <%= link_to'Mentions légales', mentions_path %>
        <a href="#">FAQ</a>
        <a href="#">Crédits</a>
        <%= link_to'Kit presse', presse_path %>
      </div>
    </div>
  </div>
  </div>
</footer>
<script>
     new WOW().init();
     </script>
     <script media="screen and (min-width: 989px)">
       wow = new WOW(
         {
           animateClass: 'animated',
           offset:       100,
           callback:     function(box) {
             console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")
           }
         }
       );
       wow.init();
     </script>
    </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
 <title><%= yield(:title) %></title>
 <meta charset="utf-8"/>
 <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
 <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1, user-scalable=no"/>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<body class="<%= controller.controller_name %>">
  <div id="layout-main-page">
    <div class="fix-menu">
    <nav id="topmenu">
    <li><a href="#" class="class-menu"><div class="line-menu elem-one"></div><div class="line-menu elem-two"></div><div class="line-menu elem-three"></div></a>
      <div id="submenu">
        <ul>
        <li class="limen"><%= link_to 'ACCUEIL', home_path %></li>
        <li class="limen"><%= link_to 'IDÉE', idea_path %></li>
        <li class="limen"><%= link_to 'LÉGENDE', legend_path %></li>
        <li class="limen"><%= link_to 'PRODUITS', store_path %></li>
        <li class="limen"><%= link_to 'POINTS DE VENTE', pointsofsale_path,  data: { no_turbolink: false } %></li>
        <li class="limen"><%= link_to 'TRAVAILLER AVEC NOUS', workwithus_path %></li>
        <li class="limen"><%= link_to 'CONTACT', contact_path %></li>
        <li class="limen"> <%= link_to image_tag("/elem/shopping-bag.png", :class =>"panier-header-menu"), current_cart %></li>
        <% if current_user && current_user.admin? %>
        <li><%= link_to'Orders', orders_path %></li>
        <li><%= link_to'Products', products_path %></li>
        <li><%= link_to'Users', users_path %></li>
        <li><%= link_to'Shops', maps_path %></li>
        <% end %>
        <% if current_user %>
        <li><p class="log-buttons"><%= button_to 'deconnexion', destroy_user_session_path, method: :delete %></p></li>
        <% else %>
        <li class="log-buttons"><p><a data-toggle="modal" data-target="#myModal2">INSCRIPTION / CONNEXION</a></p></li>
        <% end %>
        <li><%= link_to instagram_path do image_tag("/elem/insta.png", onmouseover: "this.src='#{asset_path('/elem/insta-hover.png')}'", onmouseout: "this.src='#{asset_path('/elem/insta.png')}'", width: '25') end %><%= link_to facebook_path do image_tag("/elem/facebook.png", onmouseover: "this.src='#{asset_path('/elem/facebook-hover.png')}'", onmouseout: "this.src='#{asset_path('/elem/facebook.png')}'", width: '13') end %></li>
      </ul>
      </div>
    </nav>
  <h1 class="top-title-menu"><%= yield(:title) %></h1>
  </div>
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
  <div class="modal-dialog" role="document" style="width: 90%; top:100px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="log-and-sign">
          <div class="container">
            <div class="row">
              <div class="col-xs-6">
                <div class="connect-account">
                  <h2>Connexion</h2>
                  <p> pour les clients ayant deja un compte</p>
                  <%= form_for(:user, url: session_path(:user)) do |f| %>
                  <div class="form-inputs">
                    <div class="form-group required">
                      <%= f.label :'E-mail', class: "control-label" %>
                      <%= f.email_field :email, class: "form-control", id: "email" %>
                    </div>
                    <div class="form-group required">
                      <%= f.label :'Mot de passe', class: "control-label" %>
                      <%= f.password_field :password, class: 'form-control', id: 'password' %>
                    </div>
                  </div>
                  <div class="form-actions">
                    <%= f.submit :"Log in" %>
                  </div>
                  <%= render "devise/shared/links" %>
                <% end %>
              </div>
            </div>
                <div class="col-xs-6">
                  <div class="create-account">
                    <div class="deport_form">
                      <h2>Creer un compte</h2>
                      <p> Merci d'entrer les informations suivantes pour creer un compte</p>
                      <%= form_for(:user, url: registration_path(:user)) do |f| %>
                        <div class="form-inputs">
                          <div class="form-group required">
                            <%= f.label :'E-mail', class: "control-label" %>
                            <%= f.email_field :email, class: "form-control", id: "email" %>
                          </div>
                          <div class="form-group required">
                            <%= f.label :'Mot de passe', class: "control-label" %>
                            <%= f.password_field :password, class: 'form-control', id: 'password' %>
                          </div>
                          <div class="form-group required">
                            <%= f.label :'Confirmation du mot de passe', class: "control-label" %>
                            <%= f.password_field :password_confirmation, class: 'form-control', id: 'password_confirmation' %>
                          </div>
                        </div>
                        <div class="actions">
                          <%= f.submit "S'inscrire" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<%= yield %>
</div>
</div>
</body>
</html>